popebu/urls.py
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.contrib import admin
from django.contrib.auth import urls
from auth.forms import AdminAuthenticationForm

admin.site.login_form = AdminAuthenticationForm
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^upload/', 'ckeditor.views.upload', name='ckeditor_upload'),
    url(r'^browse/', 'ckeditor.views.browse', name='ckeditor_browse'),
    url(r'^admin_tools/', include('admin_tools.urls')),
    url(r'^password_change/$', 'django.contrib.auth.views.password_change', name='password_change'),
    url(r'^password_change/done/$', 'django.contrib.auth.views.password_change_done', name='password_change_done'),
    url(r'^password_reset/$', 'django.contrib.auth.views.password_reset', name='password_reset'),
    url(r'^password_reset/done/$', 'django.contrib.auth.views.password_reset_done', name='password_reset_done'),
    url(r'^reset/(?P<uidb36>[0-9A-Za-z]{1,13})-(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', 'django.contrib.auth.views.password_reset_confirm_uidb36'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', 'django.contrib.auth.views.password_reset_confirm', name='password_reset_confirm'),
    url(r'^reset/done/$', 'django.contrib.auth.views.password_reset_complete', name='password_reset_complete'),
    url(r'^search/', include('haystack.urls')),
)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DATABASES['default']['NAME']:
    urlpatterns += patterns('', url(r'', include('widgets.urls')))
else:
    urlpatterns += patterns('', url(r'', 'setup.views.setup',))

setup/forms.py
# -*- coding: utf-8 -*-
from django import forms
from popebu import messages
from django.utils.translation import ugettext_lazy as _
import MySQLdb


class SetupForm(forms.Form):
    debug = forms.BooleanField(
        label='Debug',
        initial=False,
        help_text='Com o Debug ativado os erros encontrados na compilação serão renderizados para o browser. Não recomendado para sites em produção pois exibide dados do servidor da aplicação.',
        required=False)
    nome = forms.CharField(
        label='Nome',
        help_text='Nome do site.')
    allowed_hosts = forms.URLField(
        label='Domínio',
        initial='http://localhost:8000',
        help_text='Domínio utilizado pelo site, como http://www.example.com')
    db_nome = forms.CharField(
        label='Banco de dados',
        help_text='Nome do banco de dados.',)
    db_user = forms.CharField(
        label='Usuário',
        help_text='Usuário para conexão no banco de dados.',)
    db_senha = forms.CharField(
        label='Senha',
        help_text='Senha de acesso do usuário do banco de dados.',
        widget=forms.PasswordInput())
    db_host = forms.CharField(
        label='Endereço',
        help_text='Endereço do banco de dados. Deixe em branco caso seja um servidor local.',
        required=False)
    db_porta = forms.CharField(
        label='Porta',
        help_text='Porta em que o serviço está em execução. Deixe em branco caso o banco esteja rodando na porta padrão (Mysql default: 3306).',
        required=False)
    recaptcha_public_key = forms.CharField(
        label='Recaptcha public key',
        help_text='Chave pública do ReCaptcha.',
        required=False)
    recaptcha_private_key = forms.CharField(
        label='Recaptcha private key',
        help_text='Chave privada do ReCaptcha.',
        required=False)
    solr_url = forms.CharField(
        label='Solr URL',
        help_text='Endereço do completo do servidor Solr, incluindo a porta em que o serviço está sendo executado.',
        required=False)
    memcached_url = forms.CharField(
        label='Memcached URL',
        help_text='Endereço do completo do servidor Memcached, incluindo a porta em que o serviço está sendo executado.',
        required=False)
    superuser_username = forms.CharField(
        label='Usuário',
        help_text='Username de super usuário.')
    superuser_senha = forms.CharField(
        label='Senha',
        help_text='Senha do super usuário.',
        widget=forms.PasswordInput())
    superuser_email = forms.EmailField(
        label='Email',
        help_text='Email do super usuário.')
    superuser_email_confirm = forms.EmailField(
        label='Confirmação do email',
        help_text='Redigite o email novamente.')
    
    def clean_superuser_email_confirm(self):
        cleaned_data = self.cleaned_data
        if 'superuser_email_confirm' in cleaned_data:
            if cleaned_data['superuser_email'] != cleaned_data['superuser_email_confirm']:
                raise forms.ValidationError(_(messages.EMAIL_ERROR))
        return cleaned_data['superuser_email_confirm']
    
    def clean_db_senha(self):
        cleaned_data = self.cleaned_data   
        if 'db_nome' in cleaned_data and 'db_user' in cleaned_data and 'db_senha' in cleaned_data: 
            params = {
                'db': cleaned_data.get('db_nome'),
                'host': cleaned_data.get('db_host', ''),
                'port': cleaned_data.get('db_porta', 3306),
                'user': cleaned_data.get('db_user'),
                'passwd': cleaned_data.get('db_senha'),                  
            }
            try:
                db=MySQLdb.connect(**params)
            except:
                raise forms.ValidationError(_(messages.INVALID_CONNECTION))
        return cleaned_data['db_senha']

setup/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render
from setup.forms import SetupForm
from popebu.conf.settings.settings_base import BASE_DIR
import os 
import json
from auth.models import UserProfile
from django.contrib.sites.models import Site
from subprocess import call
from django.http import HttpResponse
import time


def setup(request):
    if request.method == 'POST':
        form = SetupForm(request.POST)
        if form.is_valid():
            # Criando arquivo de settings
            file = open(os.path.join(BASE_DIR, 'popebu', 'settings.py'), 'w+')
            file.write('from popebu.conf.settings.settings_base import *\n')
            
            data = form.cleaned_data
            file.write('DEBUG = %s\n' % data['debug'])
            file.write('ALLOWED_HOSTS = ["%s"]\n' % data['allowed_hosts'].replace('http://', '').replace('https://', '')[:-1])
            file.write('RECAPTCHA_PUBLIC_KEY = "%s"\n' % data['recaptcha_public_key'])
            file.write('RECAPTCHA_PRIVATE_KEY = "%s"\n' % data['recaptcha_private_key'])
            
            database = {}
            database['default'] = {}
            database['default']['ENGINE'] = 'django.db.backends.mysql'
            database['default']['NAME'] = data['db_nome']
            database['default']['USER'] = data['db_user']
            database['default']['PASSWORD'] = data['db_senha']
            database['default']['HOST'] = data['db_host']
            database['default']['PORT'] = data['db_porta']
            file.write('DATABASES = %s\n' % json.dumps(database))
            
            if data['solr_url']:
                haystack = {}
                haystack['default'] = {}
                haystack['default']['ENGINE'] = 'haystack.backends.solr_backend.SolrEngine'
                haystack['default']['URL'] = data['solr_url']
                file.write('HAYSTACK_CONNECTIONS = %s\n' % json.dumps(haystack))
            
            if data['memcached_url']:
                cache = {}
                cache['default'] = {}
                cache['default']['BACKEND'] = 'django.core.cache.backends.memcached.MemcachedCache'
                cache['default']['LOCATION'] = data['memcached_url']
                cache['default']['TIMEOUT'] = '600'
                file.write('CACHES = %s\n' % json.dumps(cache))
                file.write('CACHE_MIDDLEWARE_SECONDS = 600\n')
                file.write('SESSION_ENGINE = "django.contrib.sessions.backends.cache"\n')
            file.close()
            
            # Preparando banco
            call(['python', 'manage.py', 'syncdb', '--noinput'])
            call(['python', 'manage.py', 'migrate'])
            call(['python', 'manage.py', 'loaddata', os.path.join(BASE_DIR, 'popebu', 'conf', 'data', '00-grupos.json')])
                        
            command = [
                'mysql',
                '-u%s' % database['default']['USER'], 
                '-p%s' % database['default']['PASSWORD'],  
                '%s' % database['default']['NAME'], ]
            if database['default']['HOST']:
                command.append('-h%s' % database['default']['HOST'])
            if database['default']['PORT']:
                command.append('-P%s' % database['default']['PORT'])
            command.append('-e')

            # Criando usuário
            user = UserProfile(
                username=data['superuser_username'],
                email=data['superuser_email'])
            user.set_password(data['superuser_senha'])            
            call(command + ['INSERT INTO auth_userprofile (username, password, email, is_staff, is_superuser, is_active) VALUES ("%s", "%s", "%s", 1, 1, 1);' % (user.username, user.password, user.email)])
            
            # Criando site
            call(command + ['INSERT INTO django_site (name, domain) VALUES ("%s", "%s");' % (data['nome'], data['allowed_hosts'])])
            
            time.sleep(5)
            return render(request, 'popebu/confirm_setup.html')
    else:
        form = SetupForm()
        
    return render(request, 'popebu/setup.html', {'form': form})

popebu/templates/popebu/confirm_setup.html
{% extends "popebu/base.html" %}
{% block head %}
{{ block.super }}
<title>Popebu | Setup</title>
<!-- Custom styles for this template -->
<link href="{{ STATIC_URL}}setup/css/main.css" rel="stylesheet">

{% endblock %}
{% block content %}
<div class="container">
    <div class="jumbotron">
        <h1>Pronto!</h1>
        <p class="lead">Agora, reinicie o servidor da aplicação e acesse &lsaquo;url&rsaquo;/admin para começar a postar!</p>
    </div>
</div><!-- /.container -->
{% endblock %}

popebu/templates/popebu/setup.html
{% extends "popebu/base.html" %}
{% block head %}
{{ block.super }}
<title>Popebu | Setup</title>
<!-- Custom styles for this template -->
<link href="{{ STATIC_URL}}setup/css/main.css" rel="stylesheet">
{% endblock %}
{% block content %}
<div class="container">
    <div class="jumbotron">
        <h1>Obrigado por utilizar o Popebu!</h1>
        <p class="lead">Agora, que tal come&ccedil;armos o seu setup?</p>
    </div>
    <hr class="featurette-divider">
    <form action="/" method="post">{% csrf_token %}
    <div class="row featurette">
        <div class="col-md-7">
           <h2 class="featurette-heading">Passo 1: <span class="text-muted">Fale-me mais sobre seu novo site.</span></h2>
           <p>Esses dados podem ser posteriormente editados. Caso o faça, lembre-se de atualizar a variável ALLOWED_HOSTS no arquivo settings.py com o novo domínio cadastrado.</p>
        </div>
        <div class="col-md-5">
           <div class="lead">
                <fieldset>
                    <label for="id_nome">Nome</label>
                    {{ form.nome }}
                    {{ form.nome.errors }}
                    <p>{{ form.nome.help_text }}</p>
                </fieldset>
                <fieldset>
                    <label for="id_allowed_hosts">Dom&iacute;nio</label>
                    {{ form.allowed_hosts }}
                    {{ form.allowed_hosts.errors }}
                    <p>{{ form.allowed_hosts.help_text }}</p>
                </fieldset>
                <fieldset>
                    <label for="id_debug">Debug</label>
                    {{ form.debug }}
                    {{ form.debug.errors }}
                    <p>{{ form.debug.help_text }}</p>
                </fieldset>
            </div>
        </div>
    </div>
    <hr class="featurette-divider">
    <div class="row featurette">
        <div class="col-md-5">
            <div class="lead">
                <fieldset>
                    <label for="id_db_nome">Nome</label>
                    {{ form.db_nome }}
                    {{ form.db_nome.errors }}
                    <p>{{ form.db_nome.help_text }}</p>
                </fieldset>
                <fieldset>
                    <label for="id_db_user">Usu&aacute;rio</label>
                    {{ form.db_user }}
                    {{ form.db_user.errors }}
                    <p>{{ form.db_user.help_text }}</p>
                </fieldset>
                <fieldset>
                    <label for="id_db_senha">Senha</label>
                    {{ form.db_senha }}
                    {{ form.db_senha.errors }}
                    <p>{{ form.db_senha.help_text }}</p>
                </fieldset>
                <fieldset>
                    <label for="id_db_host">Endere&ccedil;o</label>
                    {{ form.db_host }}
                    {{ form.db_host.errors }}
                    <p>{{ form.db_host.help_text }}</p>
                </fieldset>
                <fieldset>
                    <label for="id_db_porta">Porta</label>
                    {{ form.db_porta }}
                    {{ form.db_porta.errors }}
                    <p>{{ form.db_porta.help_text }}</p>
                </fieldset>
            </div>
        </div>
        <div class="col-md-7">
           <h2 class="featurette-heading">Passo 2: <span class="text-muted">Um banco para dados seria bom...</span></h2>
           <p>Informe um banco de dados MySQL. </p>        
        </div>
    </div>
    <hr class="featurette-divider">
    <div class="row featurette">
        <div class="col-md-7">
            <h2 class="featurette-heading">Passo 3: <span class="text-muted">Extras! Extras! Extras!</span></h2>
            <p>Para garantir que nenhuma ferramenta de automação acesse a área administrativa do Popebu indevidamente, após três tentativas mal sucedidas é exibido um Captcha para garantir a segurança do sistema. Acesse o site do <a href="https://www.google.com/recaptcha" target="_blank">ReCaptcha</a> para gerar suas chaves de segurança.</p>
            <p>O <a href="http://lucene.apache.org/solr/" target="_blank">Solr</a> é uma ferramenta para busca semântica. Saiba mais lendo a sua <a href="http://lucene.apache.org/solr/tutorial.html" target="_blank">documentação</a>.</p>
            <p>Já o <a href="http://memcached.org/" target="_blank">Memcached</a> é uma ferramenta que auxilia no cacheamento dos dados da sessão. Saiba mais lendo a sua <a href="http://code.google.com/p/memcached/wiki/NewStart" target="_blank">documentação</a>.</p>
        </div>
        <div class="col-md-5">
            <div class="lead">
                <fieldset>
                    <label for="id_recaptcha_public_key">Public Key</label>
                    {{ form.recaptcha_public_key }}
                    {{ form.recaptcha_public_key.errors }}
                    <p>{{ form.recaptcha_public_key.help_text }}</p>
                </fieldset>
                <fieldset>
                    <label for="id_recaptcha_private_key">Private Key</label>
                    {{ form.recaptcha_private_key }}
                    {{ form.recaptcha_private_key.errors }}
                    <p>{{ form.recaptcha_private_key.help_text }}</p>
                </fieldset>
                <fieldset>
                    <label for="id_solr_url">Solr</label>
                    {{ form.solr_url }}
                    {{ form.solr_url.errors }}
                    <p>{{ form.solr_url.help_text }}</p>
                </fieldset>
                <fieldset>
                    <label for="id_memcached_url">Memcached</label>
                    {{ form.memcached_url }}
                    {{ form.memcached_url.errors }}
                    <p>{{ form.memcached_url.help_text }}</p>
                </fieldset>
            </div>
        </div>
    </div>
    <hr class="featurette-divider">
    <div class="row featurette">
        <div class="col-md-5">
            <div class="lead">
                <fieldset>
                    <label for="id_superuser_username">Username</label>
                    {{ form.superuser_username }}
                    {{ form.superuser_username.errors }}
                    <p>{{ form.superuser_username.help_text }}</p>
                </fieldset>
                <fieldset>
                    <label for="id_superuser_senha">Senha</label>
                    {{ form.superuser_senha }}
                    {{ form.superuser_senha.errors }}
                    <p>{{ form.superuser_senha.help_text }}</p>
                </fieldset>
                <fieldset>
                    <label for="id_superuser_email">Email</label>
                    {{ form.superuser_email }}
                    {{ form.superuser_email.errors }}
                    <p>{{ form.superuser_email.help_text }}</p>
                </fieldset>
                <fieldset>
                    <label for="id_superuser_email">Confirme email</label>
                    {{ form.superuser_email_confirm }}
                    {{ form.superuser_email_confirm.errors }}
                    <p>{{ form.superuser_email_confirm.help_text }}</p>
                </fieldset>
            </div>
        </div>
        <div class="col-md-7">
            <h2 class="featurette-heading">Passo 4: <span class="text-muted">Super-user!</span></h2>
            <p>Utilize um email válido para cadastrar o seu usuário pois o mesmo será utilizado para o reenvio da sua senha caso a esqueça.</p>
        </div>
    </div>
    <p align="right"><input class="btn btn-primary btn-lg" type="submit" value="Enviar" /></p>
    <hr class="featurette-divider">
    </form>
</div><!-- /.container -->
{% endblock %}